### ISSUE TITLE
Erro on rendering toguro's messages 

### ISSUE THREAD

**Issue by Thiago-spart** [lucasfcosta/toguro-ipsum#2]
# Overview

It seems like a request error, I turned off the adBlock to see if it's some sort of an ad error but it didn't work too.
Some of the errors are ``Minified React error`` and ``Uncaught ReferenceError: sa_event is not defined``(this one especially when I click to request the text), and the ad error ``Failed to load resource: net::ERR_BLOCKED_BY_ADBLOCKER``.

## Video

https://user-images.githubusercontent.com/63079213/190868199-d8982e7b-36dd-4365-892d-4835a00e4a26.mp4

**Comment by lucasfcosta** [comment]
O shape arrumou por mim.
